### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ybinrain** [sourcegraph/webloop#17]
# github.com/sourcegraph/webloop/cmd/static-reverse-proxy
/home/ybin/apps/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-470351107/000009.o：in function ‘removeClosure’中：
/tmp/go-build851580455/github.com/gotk3/gotk3/glib/_obj/_cgo_export.c:10: multiple definition of `removeClosure'
/tmp/go-link-470351107/000001.o:/tmp/go-build851580455/github.com/conformal/gotk3/glib/_obj/_cgo_export.c:10：first definition
/tmp/go-link-470351107/000009.o：in function ‘goMarshal’中：
/tmp/go-build851580455/github.com/gotk3/gotk3/glib/_obj/_cgo_export.c:23: multiple definition of `goMarshal'
/tmp/go-link-470351107/000001.o:/tmp/go-build851580455/github.com/conformal/gotk3/glib/_obj/_cgo_export.c:23：first definition
collect2: error：ld return 1

**Comment by paultag** [comment]
This will be fixed if https://github.com/sourcegraph/go-webkit2/pull/32 gets merged

**Comment by sqs** [comment]
Merged sourcegraph/go-webkit2#32. Closing. Please reopen if this continues to be an issue.
