### ISSUE TITLE
Hang on Arch Linux

### ISSUE THREAD

**Issue by zachlatta** [sourcegraph/webloop#6]
The headless example program in the README silently hangs on Arch Linux 64bit.

Repro steps:
1. Make sure you are running
2. Install https://www.archlinux.org/packages/extra/x86_64/webkitgtk/
3. Run the headless example program from the README (https://github.com/sourcegraph/webloop#operating-a-headless-webkit-and-running-arbitrary-javascript-in-the-page)
4. Notice that the program silently hangs

System dump: https://gist.github.com/zachlatta/2fe43a3044c5dfbdb8dd

**Comment by Somesh** [comment]
Did any one encountered similar issue with https://github.com/sourcegraph/webloop#rendering-static-html-from-a-dynamic-single-page-angularjs-app
