### ISSUE TITLE
Error: Package javascriptcoregtk-3.0 was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by hyp530** [sourcegraph/webloop#9]
There's an error when package webkit2 is imported as follows. Could you kindly help with it? It seems that I need to install package javascriptcoregtk-3.0 for my windows 7 (64bit) , but I don't know how to do it.

Errors:

c:/go/bin/go.exe build  [D:/Desktop/All_Projects/test]
# pkg-config --cflags javascriptcoregtk-3.0

Package javascriptcoregtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `javascriptcoregtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'javascriptcoregtk-3.0' found
exit status 1

**Comment by darilldrems** [comment]
I got the same error on elementary os which is linux operating system.

**Comment by arsham** [comment]
(on Arch Linux): I just installed webkitgtk (v 2.4.9-2) which contains /usr/lib/libjavascriptcoregtk-3.0.so . Now I'm getting: 

> No package 'webkit2gtk-3.0' found

I found [this](https://github.com/ValHue/AUR-PKGBUILDs/blob/master/gnome-books-git/PKGBUILD) link (I don't remember the source, sorry) which suggests:

> sed -i "s|webkit2gtk-3.0|webkit2gtk-4.0|g" configure.ac

There is also this file in my file system: 

> /usr/lib/libwebkit2gtk-4.0.so

which belongs to webkit2gtk package (v 2.10.3-2). Is this a **version** mismatch?

At this point I've got nothing :disappointed:. I hope someone can resolve this issue.

Thank you

**Comment by maximih** [comment]
I have the same issue on Arch linux. As mentioned before, it seems to be a version incompatibility:
```
[mx@sentinel ~]$ pkg-config --cflags javascriptcoregtk-4.0
-I/usr/include/webkitgtk-4.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
[mx@sentinel ~]$ 
[mx@sentinel ~]$ 
[mx@sentinel ~]$ pkg-config --cflags javascriptcoregtk-3.0
Package javascriptcoregtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `javascriptcoregtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'javascriptcoregtk-3.0' found
```

I tried to create a symlink and it seems to work now:

```
sudo ln -s /usr/lib/pkgconfig/javascriptcoregtk-4.0.pc /usr/lib/pkgconfig/javascriptcoregtk-3.0.pc
```
